[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://zappayapp-ie9d2.ondigitalocean.app/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "https://zappayapp-ie9d2.ondigitalocean.app/health"
  status = 200

[[redirects]]
  from = "/rapyd-health"
  to = "https://zappayapp-ie9d2.ondigitalocean.app/rapyd-health"
  status = 200

[[redirects]]
  from = "/email-test"
  to = "https://zappayapp-ie9d2.ondigitalocean.app/email-test"
  status = 200

[[redirects]]
  from = "/sms-test"
  to = "https://zappayapp-ie9d2.ondigitalocean.app/sms-test"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
