name: zappay-api
services:
- name: api
  source_dir: /backend
  github:
    repo: vaing85/zappay-app
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3001"
  - key: HOST
    value: "0.0.0.0"
  - key: DB_URL
    value: ${db.DATABASE_URL}
  - key: REDIS_URL
    value: ${redis.DATABASE_URL}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: REFRESH_TOKEN_SECRET
    value: ${REFRESH_TOKEN_SECRET}
  - key: SENDGRID_API_KEY
    value: ${SENDGRID_API_KEY}
  - key: FROM_EMAIL
    value: noreply@zappay.com
  - key: FROM_NAME
    value: ZapPay
  - key: TWILIO_ACCOUNT_SID
    value: ${TWILIO_ACCOUNT_SID}
  - key: TWILIO_AUTH_TOKEN
    value: ${TWILIO_AUTH_TOKEN}
  - key: TWILIO_PHONE_NUMBER
    value: ${TWILIO_PHONE_NUMBER}
  - key: CORS_ORIGIN
    value: https://zappay.site,https://www.zappay.site,https://api.zappay.site,https://zappay.com,https://www.zappay.com
  - key: FRONTEND_URL
    value: https://zappay.site
  - key: LOG_LEVEL
    value: info
  - key: RATE_LIMIT_MAX_REQUESTS
    value: "200"
  - key: MAX_REQUEST_SIZE
    value: "10485760"
  - key: BCRYPT_ROUNDS
    value: "12"
  - key: DB_SSL_REJECT_UNAUTHORIZED
    value: "false"
  - key: RAPYD_ACCESS_KEY
    value: ${RAPYD_ACCESS_KEY}
  - key: RAPYD_SECRET_KEY
    value: ${RAPYD_SECRET_KEY}
  - key: RAPYD_BASE_URL
    value: https://api.rapyd.net
  - key: RAPYD_WEBHOOK_SECRET
    value: ${RAPYD_WEBHOOK_SECRET}
  - key: RAPYD_MERCHANT_ACCOUNT
    value: ${RAPYD_MERCHANT_ACCOUNT}
  - key: RAPYD_P2P_ENABLED
    value: "true"
  - key: ALLOWED_ORIGINS
    value: https://zappay.site,https://www.zappay.site,https://api.zappay.site,https://zappay.com,https://www.zappay.com
  - key: RATE_LIMIT_WINDOW_MS
    value: "900000"
  - key: JWT_EXPIRES_IN
    value: "7d"
  - key: BCRYPT_ROUNDS
    value: "12"
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  alerts:
  - type: cpu
    disabled: false
    value: 80
  - type: memory
    disabled: false
    value: 80
  - type: disk
    disabled: false
    value: 80
  - type: latency
    disabled: false
    value: 500
  - type: error_rate
    disabled: false
    value: 0.05

databases:
- name: db
  engine: PG
  version: "15"
  size: db-s-1vcpu-1gb
  num_nodes: 1
  region: nyc1

- name: redis
  engine: REDIS
  version: "7"
  size: db-s-1vcpu-1gb
  num_nodes: 1
  region: nyc1